# Generated by Django 3.1.1 on 2020-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200919_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/media/default_profile.jpg/', upload_to='profiles'),
        ),
    ]
