# Generated by Django 3.1.1 on 2020-09-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200922_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default_profile.jpg/', upload_to='profiles'),
        ),
    ]
