# Generated by Django 3.1.1 on 2020-10-01 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='CommentLike',
        ),
    ]
